name: Run Cucumber Tests

on:
  push:
    branches:
      - main  # Workflow dijalankan saat push ke branch 'main'
  pull_request:
    branches:
      - main  # Workflow dijalankan saat ada pull request ke branch 'main'

jobs:
  cucumber-test:
    runs-on: ubuntu-latest  # Menjalankan workflow pada runner Ubuntu

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup JDK 11 dengan AdoptOpenJDK
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'           # Menentukan versi JDK yang diinginkan
          distribution: 'temurin' # Menentukan distribusi JDK
          java-package: jdk
          architecture: x64
          check-latest: false

      # Langkah 3: Install dependencies menggunakan Maven
      - name: Install dependencies
        run: mvn clean install -DskipTests  # Install dependencies tanpa menjalankan tes

      # Langkah 4: Jalankan Cucumber tests menggunakan Maven
      - name: Run Cucumber tests
        run: mvn test  # Jalankan semua tes, termasuk tes Cucumber

      # Langkah 5: Upload laporan Cucumber ke GitHub (opsional)
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results # Path ke laporan tes Cucumber

      # Step 6: Download Allure results (from uploaded artifact)
      - name: Download Allure results artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      # Step 7: Generate Allure report
      - name: Generate Allure report
        run: allure generate ./allure-results --clean

      # Step 8: Serve Allure report
      - name: Serve Allure report
        run: allure open ./allure-report  # Open the generated Allure report in the GitHub runner

      # Step 9: Clean up downloaded artifact (optional)
      - name: Clean up downloaded artifact
        run: rm -rf ./allure-results  # Clean up the results folder after use