name: Run Cucumber Tests

on:
  push:
    branches:
      - main  # Workflow dijalankan saat push ke branch 'main'
  pull_request:
    branches:
      - main  # Workflow dijalankan saat ada pull request ke branch 'main'

jobs:
  cucumber-test:
    runs-on: ubuntu-latest  # Menjalankan job di runner Ubuntu

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Langkah 2: Setup JDK (misalnya JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Menambahkan distribusi JDK
          java-package: jdk
          architecture: x64
          check-latest: false

      # Langkah 3: Install dependencies menggunakan Maven
      - name: Install dependencies
        run: mvn clean install -DskipTests  # Menginstal dependensi tanpa menjalankan tes

      # Langkah 4: Jalankan Cucumber tests menggunakan Maven
      - name: Run Cucumber tests
        run: mvn test  # Jalankan tes menggunakan Maven

      # Langkah 5: Upload laporan Cucumber (opsional)
#      - name: Upload Cucumber report to GitHub
#        uses: actions/upload-artifact@v3
#        with:
#          name: cucumber-report  # Nama artefak
#          path: target/cucumber-report.html  # Path ke laporan tes Cucumber